CREATE TABLE [dbo].[BTGoldLoanLeadDocumentPOIPOAFiles]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[LeadId] BIGINT NOT NULL REFERENCES BtgoldLoanLead(ID),
	[IsPOI] BIT NOT NULL DEFAULT(0),
	[FileName] NVARCHAR(MAX) NOT NULL,
    [FileType] NVARCHAR(500) NULL,
    [Path] NVARCHAR(MAX) NOT NULL,
	
)
