CREATE TABLE [dbo].[UserAvailability]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] BIGINT NOT NULL, 
    [MondayST] TIMESTAMP NULL, 
    [MondayET] TIMESTAMP NULL, 
    [TuesdayST] TIMESTAMP NULL, 
    [TuesdayET] TIMESTAMP NULL,     
    [WednesdayST] TIMESTAMP NULL, 
    [WednesdayET] TIMESTAMP NULL,  
    [ThursdayST] TIMESTAMP NULL, 
    [ThursdayET] TIMESTAMP NULL,  
    [FridayST] TIMESTAMP NULL, 
    [FridayET] TIMESTAMP NULL,  
    [SaturdayST] TIMESTAMP NULL, 
    [SaturdayET] TIMESTAMP NULL, 
    [SundayST] TIMESTAMP NULL, 
    [SundayET] TIMESTAMP NULL, 
    [Capacity ] INT NULL, 
    [PinCode] BIGINT NULL, 
    [DistrictId] INT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [IsDelete] BIT NOT NULL DEFAULT 0, 
    [CreatedOn] DATETIME NOT NULL DEFAULT GetDate(), 
    [ModifiedOn] DATETIME NULL, 
    CONSTRAINT [FK_UserAvailability_ToTable] FOREIGN KEY ([UserId]) REFERENCES [UserMaster](Id),
)
