CREATE TABLE [dbo].[UserOTP]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,    
	[Mobile] NVARCHAR(20) NOT NULL , 
	[OTP]  NVARCHAR(MAX),   
    [IsVerify] BIT NOT NULL DEFAULT 0, 
    [SessionStartOn] DATETIME NOT NULL DEFAULT GETDATE(), 
    [ExpireOn] DATETIME NULL, 
    [MessgeId] BIGINT NULL , 
    
)
